mqtt:
  broker:
  port: 1883
  topic_prefix: glyphic
  username: ""  # Optional
  password: ""  # Optional
  client_id: glyphic_client
  keepalive: 60

logging:
  level: INFO
  file: logs/glyphic.log
  max_size: 1048576
  backup_count: 3

macros:
  folders:
    - macros
  auto_reload: true
  reload_interval: 30